version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    environment:
      - NODE_ENV=prod
    restart: always

    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50' 
          memory: 512M 
        reservations:
          cpus: '0.25'
          memory: 256M