version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=dev

    command: >
      sh -c "npm run dev -- --no-sandbox --disable-dev-shm-usage"
    volumes:
      - .:/home/nodeuser/app
      - /home/nodeuser/app/node_modules